### ISSUE TITLE
'passed training' missing for eligibility

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/amy#1054]
I just came across a trainee that has passed SWC homework, Discussion and SWC Demo, but is not eligible to be certified due to not having passed 'Training' - even though there is a TTT workshop entry in the 'Training' field. Is this an intended possibility? I can give details on who it was in an email if needed.

**Comment by gvwilson** [comment]
Definitely sounds like a bug - please send details to @pbanaszkiewicz 
and @chrismedrela.

**Comment by lexnederbragt** [comment]
Email sent.

**Comment by chrismedrela** [comment]
> Is this an intended possibility?

Yes. One thing is whether somebody is matched with a training (that is, he is a learner at a TTT workshops) and a completely independent thing is whether somebody passed/failed the training. The workflow is:

1.  applicants are matched with a TTT training (so that there is an entry in the "training" column):
![image](https://cloud.githubusercontent.com/assets/1645996/19619308/602867ee-9864-11e6-9cf1-d913c44d5307.png)

1.  the training runs;
1.  at the end of the training, the instructor indicates who passed or failed the training (so that there is greed or red "training" label in "progress" column):
![image](https://cloud.githubusercontent.com/assets/1645996/19619304/538ab08c-9864-11e6-89ba-b0ae58932802.png)

**Comment by chrismedrela** [comment]
Please reopen if you want to change the workflow.

**Comment by gvwilson** [comment]
I think we need a way to say, "Give all of the learners in this workshop *except* the ones I've ticked a marker to say they've completed training."  I.e., the usual case is that all of the people registered for a training get a "completed training" progress marker, but we need to indicate that a handful don't (because they were no-shows or skipped out early or whatever).

**Comment by gvwilson** [comment]
I think we need a way to say, "Give all of the learners in this workshop *except* the ones I've ticked a marker to say they've completed training."  I.e., the usual case is that all of the people registered for a training get a "completed training" progress marker, but we need to indicate that a handful don't (because they were no-shows or skipped out early or whatever).

**Comment by gvwilson** [comment]
Never mind, I just figured out how to do it - thanks.
