### ISSUE TITLE
Configure Travis so that it tests merged changes

### ISSUE THREAD

**Issue by chrismedrela** [swcarpentry/amy#1066]
Right now, if somebody proposes merging `my-patch` branch, Travis runs tests on this branch. Instead, we should first merge the branch with `develop` and then run tests. If both branches have new migrations, running tests without merging doesn't detect conflicting migrations.

**Comment by narayanaditya95** [comment]
Suggested a fix at #1073

**Comment by narayanaditya95** [comment]
As @pbaneswicz pointed out at #1073, Travis does merge the develop branch into the branch contained in the PR.
However, our problem is somewhat different. Although a PR can be marked safe by Travis today (after merging from develop), a change to develop tomorrow that does not cause a merge conflict with the PR may lead to a migration clash or other test failures. I think the solution to this issue is to somehow rerun the Travis test suite just before merge. Does the web interface allow us to do that?

**Comment by chrismedrela** [comment]
> Yes, it does. So, we must manually restart the test suite for a PR after every change to the develop branch to ensure that the tests always pass.

How can we do that?

**Comment by narayanaditya95** [comment]
At the PR page, use the following workflow:

1. Click of "Show all checks"
2. Click on "Details" to the right of the Travis test list option.
3. At the build page of Travis, click on "Restart build".

**Comment by chrismedrela** [comment]
@narayanaditya95 thank you very much for instructions. I'm closing it, because we found the solution: we need to manually restart build before merging.
