### ISSUE TITLE
Validating GitHub user names

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1107]
If AMY is going to allow login with GitHub usernames then it needs to validate for this.  I believe that only alphanumeric and underscores are allowed but  I can't find documentation on this.

**Comment by chrismedrela** [comment]
I've manually corrected invalid GitHub usernames for the following people in production data: 
345, 2851, 5268, 6615, 8283, 9332, 1083, 10940, 12553.

The following people have still their GitHub usernames invalid: 10345, 10483, 10493, 12206, 13099.

**Comment by chrismedrela** [comment]
Profile update no. 487 has invalid GitHub username.

The following training requests have invalid GitHub username: 98, 115, 122, 130, 184, 192, 225, 251, 258, 260, 287, 289, 308, 312, 319, 329, 331.

**Comment by chrismedrela** [comment]
I've manually corrected invalid GitHub usernames for the following training requests: 122, 130, 192, 225, 251, 258, 260, 287, 289, 319, 329, 331.

I propose that we fix the remaining:

- 5 Person entries (10345, 10483, 10493, 12206, 13099) and
- 5 TrainingRequests entries (98, 115, 184, 308, 312)

with invalid GitHub username by immediately removing their GitHub username and emailing these people asking them for a correct GitHub username.

In the case of profile update no. 487, IMO it can be discarded since we don't have this person in our production DB. We should also probably contact this person by email. 

@maneesha any opinions? Who should email these people?

**Comment by narayanaditya95** [comment]
@chrismedrela 
I am not sure if you are currently making use of PyGitHub, but its [search_user_by_email](http://pygithub.readthedocs.io/en/latest/github.html#github.MainClass.Github.legacy_search_user_by_email) can be quite helpful.

**Comment by chrismedrela** [comment]
Ref #1139.
