### ISSUE TITLE
Inconsistencies when using "import from URL"

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1169]
When on new event page (https://amy.software-carpentry.org/workshops/events/add/), clicking "Import from URL" tells you "Use the URL of the event's website, e.g. http://swcarpentry.github.io/workshop-template/ or http://www.datacarpentry.org/workshop/, and not the URL of its GitHub repository."

However when accepting a workshop request (https://amy.software-carpentry.org/workshops/request/XXX/accept/), it says "Either URL to the event's website or to it's repository index.html will work."

It seems like a link to the repo, and not necessarily the index.html file will work for the "accept workshop" page to populate the form.
However, the "URL" field of the form gets populated with the link to the repo, and then the form fails validation.  So if a user enters the github repo rather than the website URL, it should not populate the URL fied.

**Comment by chrismedrela** [comment]
So there are actually two issues:

1. Inconsistent and misleading help texts below "url" field in "import from URL" modal. Here is PR: #1170.

2. Validation error in event form because of autofilling-in URL field. In that case, we can convert a link to GitHub repo to a link to website. This can be done manually (in that case we probably need to add a hint to error message) or automatically by AMY. @maneesha any opinions?

**Comment by chrismedrela** [comment]
@maneesha any opinions on the second issue?

**Comment by chrismedrela** [comment]
I'm reopening this, because #1170 solves only the first issue.
