### ISSUE TITLE
Get attendance count from list of learners - not working for TTT?

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1177]
Is this not working for TTT events?  
See for example
https://amy.software-carpentry.org/workshops/event/2017-02-21-online-instructor-training/
and 
https://amy.software-carpentry.org/workshops/event/2017-03-24-ttt-upr/

**Comment by chrismedrela** [comment]
"Ask for attendance" button is enabled if and only if the attendance is unknown or is equal zero. Should it be _always_ enabled?

**Comment by maneesha** [comment]
This is not about the "Ask for attendance" button.  Attendance count is supposed to populate from the list of learners.  That does not seem to be working.

**Comment by chrismedrela** [comment]
@narayanaditya95 what is the reason to only increase attendance count [here](https://github.com/swcarpentry/amy/blob/f5f1301e197ee5a203172fe4beaf9ee9a31269b0/workshops/models.py#L1137)? Why don't we update the count when it decreases?

Also, why do we store the count in a field instead of computing it on demand? Is it for speed?

**Comment by chrismedrela** [comment]
@maneesha it has nothing to do with TTT, it's a cache invalidation problem. As a workaround, you can edit and save an event when you want to update the count.

**Comment by chrismedrela** [comment]
@narayanaditya95 ping

**Comment by narayanaditya95** [comment]
@chrismedrela 

> @narayanaditya95 what is the reason to only increase attendance count here?

This snippet of code was previously being called during the POST requests for `event_edit` view. I modified it to be invoked at `save` method of the Event model. This cache invalidation problem probably existed then as well, I never paid enough attention to it.

> Why don't we update the count when it decreases?

Same. I never looked into that during the refactor.

>Also, why do we store the count in a field instead of computing it on demand? Is it for speed?

You are right, the entire cache invalidation problem wouldn't have existed if the `attendance` attribute was calculated on demand.

**Comment by chrismedrela** [comment]
@narayanaditya95 thank you for your feedback. It all makes sense to me now.

**Comment by chrismedrela** [comment]
Right now, `attendance` can be 1) entered manually or 2) computed from learner tasks and overridden. I propose that we leave `attendance` for storing "manual" values and create `real_attendance` property that returns maximum of attendance and number of learner tasks.

@pbanaszkiewicz @narayanaditya95 any opinions?

**Comment by chrismedrela** [comment]
And maybe rename the field to `manual_attendance` and the property to `computed_attendance`.

**Comment by narayanaditya95** [comment]
>Right now, attendance can be 1) entered manually or 2) computed from learner tasks and overridden. I propose that we leave attendance for storing "manual" values and create real_attendance property that returns max(self.attendance, number_of_learner_tasks).

That sounds right. +1

**Comment by chrismedrela** [comment]
@narayanaditya95  thank you for your feedback. :-)

**Comment by pbanaszkiewicz** [comment]
@maneesha this is an old issue, but here's a short recap: event attendance is entered manually to `Event.attendance` field. However, whenever the event is saved (and only then!), and a number of corresponding learner tasks is higher than the entered value, the `Event.attendance` is set to that number.

This is flawed because 1) update to `Event.attendance` happens only when `Event` is saved, and 2) the number of learner tasks is preferred only when it's higher than actual `Event.attendance`.

Here are possible improvements to this feature:
1.  if `Event.attendance` is NULL, count attendance from learner tasks; otherwise show attendance as `Event.attendance`.
2. only count attendance from learner tasks, don't allow for entering manual attendance number
3. compute attendance as `max(Event.manual_attendance, learner_tasks.count)`

Please decide which one you want me to implement. For now I'm deferring this issue to the next release.

**Comment by maneesha** [comment]
Thanks for bringing this back up again.  We should go with option 3.  I actually thought that's what it was all along :-).
