### ISSUE TITLE
Can't edit person

### ISSUE THREAD

**Issue by apawlik** [swcarpentry/amy#1185]
I lost the access(?) to edit a person. I.e. for some of the Instructor Training Trainees I wanted to add a note that they will be late with checkout because of whatever reason they emailed me about but when I click "Edit" on the person I get 403 Forbidden. I used to be able to edit (I think I'm an admin).

**Comment by chrismedrela** [comment]
@apawlik please check now. As a workaround, I've given you superuser status.

This bug affects all people who don't have superuser status. This is because of [this line](https://github.com/swcarpentry/amy/blob/f5f1301e197ee5a203172fe4beaf9ee9a31269b0/workshops/views.py#L730). The permission name should be `workshops.change_person`, not `workshops.edit_person`.
