### ISSUE TITLE
Unifying workshops and training events

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#132]
This subsumes #29 (recording instructors for training events), #31 (recording training events as workshops), #32 (displaying training event completion rates), #33 (showing whether training counts toward an instructor badge), and #63 (do we need a separate table for training cohorts).

Amy currently represents workshops and instructor training events using completely separate models.  @wking has suggested unifying them; I agree that makes sense, but want to think through the implications before diving in.

Background:

*   A regular workshop is represented by an `Event` instance.
*   The things people can do at regular workshops (instructor, helper, learner, organizer) are enumerated by `Role`.
*   What a particular person did at a particular event is recorded by `Task`.
*   A specific offering of instructor training is recorded by `Cohort`.
*   Someone's instructor training status (in-progress, complete, incomplete) is enumerated by `TraineeStatus`.
*   Someone's participation in a particular round of instructor training is recorded by `Trainee`.

Translations:

*   `Event` and `Cohort` have start dates, venues, and slugs.
*   `Cohort` doesn't have most of the other things `Event` has, but they can be filled in:
    *   `published` is `True`.
    *   `project` (which enumerates SWC, DC, etc.) can be made `TTT` (train the trainers).
    *   `organizer` can be `software-carpentry.org`
    *   `url` can be NULL (or I can retroactively create pages for instructor training sessions).
    *   `reg_key` can be NULL.
    *   `attendance` can be the number who enrolled.
    *   `admin_fee` can be $0.0.
    *   `notes` can be empty.
*   One special case: `Cohort` doesn't have an end date right now; instead, it has an `active` field to show whether some people are still in training in that cohort.  As @wking pointed out, we could use an end date instead to show that a round of training has ended.  The only trick with this is that we don't know end dates for instructor training in advance (online courses can drag one).  However, `enddate` can already be NULL, so that seems straightforward.
*   `Cohort` *does* have a `qualifies` field to show whether this training qualifies someone to become an instructor.  We can get rid of that and simply mark people who took part in non-qualifying training rounds as done, then not issue them a badge.

The harder part is figuring out what to do about `TraineeStatus`.  The simplest answer is, don't bother, since we can infer status as follows:

*   registered = listed as a learner in a training event that hasn't started yet
*   in_progress = listed as a learner in a training event that has started but hasn't finished
*   complete = listed as a learner in a training event *and* have an instructor badge (but see below)
*   incomplete = listed as a learner in a training event that has finished, but don't have a badge (but see below)

However, this isn't completely accurate: someone may enrol in a training event, fail to complete, then enrol in a later one and complete that.  We need to track outcomes on a per-cohort basis, so a more complex possibility is to add another possibility to the `Role` enumeration: `incomplete`.  Someone would then be listed as either `learner` or `incomplete` for a particular training event.  This is more accurate (and removes the need for inference), but now we have an enumeration state that only applies to participants in training events, not in regular workshops.

**Comment by wking** [comment]
On Sat, Jan 10, 2015 at 05:43:50AM -0800, Greg Wilson wrote:
> * `url` can be NULL (or I can retroactively create pages for
>   instructor training sessions).

I'd just set it to NULL, since events without public websites should
be fine.

>     *   `attendance` can be the number who enrolled.

I think attendance should be the number who *attended*, but see #64
for more finely-grained attendance details.  If we don't have the
information to distinguish between enrollees and attendees, then using
enrollees for attendance is an acceptable hack.

> * One special case: `Cohort` doesn't have an end date right now;
>   instead, it has an `active` field to show whether some people are
>   still in training in that cohort.  As @wking pointed out, we could
>   use an end date instead to show that a round of training has
>   ended.  The only trick with this is that we don't know end dates
>   for instructor training in advance (online courses can drag one).
>   However, `enddate` can already be NULL, so that seems
>   straightforward.

And you only need to use NULL when you can't even guess the end date
(which is Event.end, the date-ness being part of that fields type and
not its name).  We can always update Event.end as we revise the
estimate.

> * `Cohort` *does* have a `qualifies` field to show whether this
>   training qualifies someone to become an instructor.  We can get
>   rid of that and simply mark people who took part in non-qualifying
>   training rounds as done, then not issue them a badge.

I wasn't aware that there were multiple rounds or classes of
instructor training.  Since we may eventually want student badges for
our regular (non-instructor-training) Events, how about:

  class Event(models.Model):
      …
      badge = models.ForeignKey(
          Badge, null=True, blank=True,
          help_text='Badge awarded to learners for completing this event')
      …

and then set Event.badge to the instructor badge for badge-worthy
instructor-training Events.  Additional out-of-class requirements
(like landing a pull request) will make this awkward, so I'd consider
adding that information to the database as well.  Maybe:

  class Event(models.Model):
      …
      additional_assignments = models.ManyToManyField(
          Assinment, blank=True,
          help_text='Additional out-of-class assignments required to recieve the badge')
      …

  class Assignment(models.Model):
      name = models.CharField(max_length=STR_MED, unique=True)

  class PersonAssignment(models.Model):
      person = models.ForeignKey(Person)
      assignment = models.ForeignKey(Assignment)
      completed = models.DateField(null=True, blank=True)

and set PersonAssignment.completed when a person completes a given
assignment.  The way I've set that up means that there's only one
Assignment for each name (e.g. if I have two Events which both require
the 'Land a SWC pull request' Assignment, the student will only have
to land one pull request to satisfy both Events).  If we want a
separate Assignment for each Event, we'd drop
Event.additional_assignments and use:

  class Assignment(models.Model):
      name = models.CharField(max_length=STR_MED)
      event = models.ForeignKey(Event)

> … a more complex possibility is to add another possibility to the
> `Role` enumeration: `incomplete`.

I think you mean Task, and I'd prefer avoiding potential
double-negatives with Task.complete.

> Someone would then be listed as either `learner` or `incomplete` for
> a particular training event.  This is more accurate (and removes the
> need for inference), but now we have an enumeration state that only
> applies to participants in training events, not in regular
> workshops.

I can imagine students at regular events skipping out early and thus
being incomplete.  It's hard to imagine an instructor or organizer
skipping out early though, so maybe just add a new Role for
‘graduate’.  Then post-workshop, any learners who successfully
attended/completed the course-work would get a new ‘graduate’ Task
associating them with the event.  I'd keep their earlier ‘learner’
Task to make it easy to make consistent queries on “folks who were
registered for this Event, regardless of whether they completed it”.
