### ISSUE TITLE
OAuth2 with GitHub

### ISSUE THREAD

**Issue by wking** [swcarpentry/amy#133]
During some offline discussion, we have:

On Fri, Jan 09, 2015 at 05:49:24PM -0800, Greg Wilson wrote:
> I am happy to defer to all of you on login mechanisms, provided we get
> GitHub ID login if it's possible to do that for unpaid accounts.

Looking at [GitHub's OAuth2 docs][docs], that means we need to [register amy][register].  To do that, we need a homepage URL and a callback URL.  Should those be:

* https://amy.software-carpentry.org/
* https://amy.software-carpentry.org/auth/github/callback

?  I haven't been able to track down whether or not this will need a paid account, so I suggest we just start working in this direction and see how far we can go for free.

Also, before we get too deep into login issues, I'd like some resolution on #70.

[docs]: https://developer.github.com/v3/oauth/
[register]: https://github.com/settings/applications/new

**Comment by narrativecraig** [comment]
Ah my assumption that registering an app required a paid account was based off of the [Register now](https://developer.github.com/program/) button on this page.

Turns out that is just for github's "Developer Program", which is a different thing entirely.

If somebody sets up the app it is super easy to turn on auth, but as @wking says, probably best to think through the DB schema fully before too much longer.

**Comment by gvwilson** [comment]
Note that this connects to #41 and #70.

**Comment by pbanaszkiewicz** [comment]
I think we can defer this till post-1.0, as - in my opinion - we had more than enough of auth for release 1.0 :)

**Comment by gvwilson** [comment]
+1

**Comment by gvwilson** [comment]
We're managing passwords ourselves now, so close this?

**Comment by pbanaszkiewicz** [comment]
1. We don't want to open AMY to instructors
2. We're self-managing now (ie. one admin can appoint other person as an admin)

Due to these two reasons, let's close this.
