### ISSUE TITLE
associated member site should only appear for ttt events

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/amy#1355]
Related to https://github.com/swcarpentry/amy/issues/1055

1) When adding tasks to a person’s record, the option to associate with a membership appears independently of whether it is a ttt event or not. Should only show up if the event is tagged as ttt.

![screen shot 2018-10-02 at 2 23 28 pm](https://user-images.githubusercontent.com/19176319/46377866-c8001f00-c64e-11e8-9c47-1213b8ab155c.png)

In the screenshot above, the field "Associated member site in TTT event"  and the check box for "Open training seat" should not appear unless the selected event has an associated TTT tag in the tags field. 

This **does not** negatively impact usability, so it is not a high priority to fix.

@karenword @sheraaron @maneesha

**Comment by ErinBecker** [comment]
@karenword

**Comment by pbanaszkiewicz** [comment]
@ErinBecker there's small issue with hiding these fields: their values should be either kept (1), or saved somewhere and retrieved when user selects a TTT event - the field values would be blank until then (2).

Now here's an interesting situation: user first selects membership and/or ticks-off "Open training seat"; then changes event so that we hide both fields (scenario 1). What happens when they click "Submit"? The form is invalid (server-side validation still will trigger for the hidden fields). But validation errors are presented right next to widgets (fields), so user won't see them because the fields are hidden. This means that (1) is not a good way to fix this issue.

Now (2) sounds like it should work - we save values from fields-to-be-hidden and clear the fields, so that there wouldn't be any errors, and when user selects a TTT event we bring back the saved values. There's a catch, unfortunately. Member site field is populated asynchronously (via "Ajax") and selecting a value in this field is not supported (https://select2.org/programmatic-control/add-select-clear-items#preselecting-options-in-an-remotely-sourced-ajax-select2).

So my suggestion is either leave the current mechanism as it is (in the worst case scenario the server-side validation will trigger an error and show the form again, see screenshot below)
![screenshot from 2018-10-06 18-07-27](https://user-images.githubusercontent.com/72821/46573250-dde54b00-c992-11e8-98bf-24ac6e2fe5bd.png)

...or let me dynamically display a warning next to "Associated member site", "Open training seat" saying that "Selected event does not have TTT tag".

@ErinBecker which option do you choose?

**Comment by ErinBecker** [comment]
Thanks for the clear response @pbanaszkiewicz. I had forgotten that you showed at our meeting that it would throw an error if you tried to associate membership with a non-TTT event. We can leave the current mechanism as is. Sorry for the confusion. @karenword @maneesha @sheraaron

**Comment by pbanaszkiewicz** [comment]
Thanks @ErinBecker. Please reopen this issue if you find it necessary.
