### ISSUE TITLE
Centrally Organized Workshop Warning

### ISSUE THREAD

**Issue by sheraaron** [swcarpentry/amy#1357]
@pbanaszkiewicz can we get a warning notice when a Membership site has gone over their allotted number of centrally organized workshops. Centrally organized workshops are when we select the host as "Administrator"?  So, if the host is selected more times than they have in their contract, a warning sign would be nice just for reference. 

@elizabethwilliams8 Please feel free to further explain if I missed anything

**Comment by pbanaszkiewicz** [comment]
@sheraaron @elizabethwilliams8 where do you want me to put this sign? After a new event is created and/or existing event is edited?

**Comment by pbanaszkiewicz** [comment]
@sheraaron @elizabethwilliams8 the field you mentioned, `Administrator`, is for organization administering the workshop; for example, most workshops in UK would be administered by SSI.

`Host` is for organization hosting (organizing) the workshop.

But, here's an issue. There's no unambiguous link between workshop and membership. The `Host` field isn't enough, because there can be multiple Memberships linked to one organization.

**Comment by sheraaron** [comment]
@pbanaszkiewicz  you are right. let's table this and @elizabethwilliams8 and I can discuss later. Thanks!

**Comment by pbanaszkiewicz** [comment]
@sheraaron thanks, closing for now, please reopen when you find necessary.
