### ISSUE TITLE
Enhancements to Find Duplicate Persons 

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#1483]
[Find Duplicate Persons](https://amy.carpentries.org/reports/duplicate_persons/) returns a long list of records that may be duplicates.

I've reviewed many of these before and decided we did not have enough information to confirm they were duplicates and so I didn't merge them.  I'd like a way to tag these so if I look for duplicates again, I don't have to see those names again.  Perhaps we could add a "Last reviewed on" date to the list, and then display records that have changed since that date.

Also, this currently allows any record to be merged up, rather than just the one that it's a possible duplicate for.  Duplicates should be grouped so we can merge them together, but issue a warning if we try to merge ones that don't appear to be like records.

**Comment by pbanaszkiewicz** [comment]
@maneesha  from your description it looks like you touch on two issues here:

1. Ability to hide records that you already reviewed.
2. Ability to merge any two selected records.

For the former, I'll add a button that you can click and it will save the timestamp for "Last reviewed on". For the latter, I'll add a checkbox or radio button to each record so that you can select it for merging.
