### ISSUE TITLE
How should we create test fixtures?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#158]
Should we create objects directly in `setUp` methods, or write out fixtures as JSON or the like?

**Comment by wking** [comment]
On Tue, Jan 20, 2015 at 06:02:01PM -0800, Greg Wilson wrote:
> Should we create objects directly in `setUp` methods, or write out
> fixtures as JSON or the like?

I like fixtures [1,2,3], because:

* That's the conventional way to do things in Django, and the fewer
  deviations less new amy devs who are already familiar with Django
  will have to learn.
* It gets the test data out of the tests themselves, so you can focus
  on the test logic there without distracting setup boilerplate.  This
  also isolates changes to the test data from changes to the test
  framework in the version control history, so it's easy to see how
  the test data has evolved over time without changes from the test
  framework distracting you (or vice versa).

[1]: https://github.com/swcarpentry/amy/pull/140#issuecomment-70692678
[2]: https://docs.djangoproject.com/en/1.7/topics/testing/tools/#topics-testing-fixtures
[3]: https://docs.djangoproject.com/en/1.7/howto/initial-data/#providing-initial-data-with-fixtures

**Comment by pbanaszkiewicz** [comment]
I like fixtures, too. In case we switch to them, can we consider generating up-to-date random fixtures in favor of distributing `db.sql` with blurred sensitive data?

This may have some impact on development:

* no need for Greg to run `migrater.py` over and over again
* no disclosing non-sensitive information, like number of people registered for specific workshop, etc.
* no more huge +- lines in commits
* more legible names / emails / notes / etc. in test data

**Comment by gvwilson** [comment]
The current tests don't use the (fuzzed) imported data - that's for 
manual testing to make sure that when we deploy, we'll actually be able 
to load real data.  I'm not a fan of testing against only random data - 
no guarantee that random exposes corner cases - but in favor of 
including some random in tests.

**Comment by pbanaszkiewicz** [comment]
Sorry, I should've specified: I'm mostly advocating random-generated fixtures for development.

For testing I can see one of two ways:

1. Write manually fixtures

2. Generate semi-random fixtures (or rather "object factories" that don't use JSON files), ie. get either random email address or random name, but not random attributes (for example `may_contact` will be `True` whenever you want).

Perhaps @wking or @sburns have more experience and opinions about generating fixtures…

**Comment by wking** [comment]
On Thu, Jan 22, 2015 at 03:52:10PM -0800, Piotr Banaszkiewicz wrote:
> 1. Write manually fixtures

This is what I recommend, and it's what we currently do in _setUpSites
and friends.  I don't expect it will be all that hard to keep the
fixtures up to date with the tests.  I don't think semi-random
fixtures will add any more robustness, and if we're generating the
random data at test-running time (instead of committing it at
test-writing time) it makes it harder for others to reproduce your
failures.

**Comment by sburns** [comment]
I think fixtures save time and some headaches. I do agree with @gvwilson about their not exploring  corner cases but that's really up the particular unittest. A lot of my edge testing looks like:

0. Load fixtures (usually with the fixtures class attr)
1. Read an object
2. Alter the tested parameter/field, save. 
3. Perform the test
4. Check that nothing blew up/proper error message/etc. 
5. Repeat 1-5 as necessary. 

To get to that initial state that both developers and the system agree on, fixtures can be very useful. 

I also advocate for manually-written fixtures but I almost always use dumpdata model --format=json --indent=2 --pk=... > fixture.json as a starting point.

**Comment by wking** [comment]
On Fri, Jan 23, 2015 at 01:24:08AM -0800, Scott Burns wrote:
> I also advocate for manually-written fixtures but I almost always
> use dumpdata model --format=json --indent=2 --pk=... > fixture.json
> as a starting point.

+1 to get the formatting, although I don't think we can trim that down
from our fuzzed data (and use Greg's Harry Potter theme, or whatever)
before committing them ;).

**Comment by pbanaszkiewicz** [comment]
New option:
In Django 1.8 we'll be able to use `TestCase.setUpTestData()` https://docs.djangoproject.com/en/dev/topics/testing/tools/#django.test.TestCase.setUpTestData
It's faster than `TestCase.setUp()` because it's run once for all tests within particular test case.

**Comment by pbanaszkiewicz** [comment]
We don't create test fixtures specifically, but use `setUp` methods instead.
