### ISSUE TITLE
Change export feature to just return the JSON

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/amy#169]
What about the export feature (http://localhost:8000/workshops/export/badges and http://localhost:8000/workshops/export/instructors) just return the JSON instead of it as part of the HTML?

This approach have some advantages:

- easy to download/copy
- increase page load
- reduce work on server side

**Comment by gvwilson** [comment]
Will that render reliable on older browsers?

**Comment by wking** [comment]
On Mon, Jan 26, 2015 at 03:44:20PM -0800, Greg Wilson wrote:
> Will that render reliable on older browsers?

I expect *all* browsers will just suggest you save something served as
application/json instead of trying to render it.  Do we expect humans
to be hitting the export endpoints with their browser?  I would have
thought they were just for programmatic access, and JSON is definitely
easier to parse than HTML ;).

**Comment by gvwilson** [comment]
It's likely that at least one human being will view it in a browser to 
copy-paste into a text file in the 'site' repo.

**Comment by wking** [comment]
On Mon, Jan 26, 2015 at 04:32:33PM -0800, Greg Wilson wrote:
> It's likely that at least one human being will view it in a browser
> to copy-paste into a text file in the 'site' repo.

I'd just add a phony 'import-amy-data' target to site's Makefile, and
use wget or curl or some such in the recipe.  If site needs the YAML,
I'd just serve the YAML (as text/x-yaml? [1]).  If site can handle
JSON, I'd rather serve JSON (it's easier to parse).  In either case, I
don't see a need for manual copy/pasting or an HTML-izing template.

[1]: http://stackoverflow.com/questions/332129/yaml-mime-type

**Comment by gvwilson** [comment]
Let's revisit post-1.0.
