### ISSUE TITLE
Add a navigation bar.

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#194]
There should be a navigation bar. For now, go to the home page and select a link.

**Comment by pbanaszkiewicz** [comment]
Can it be in the topbar that appears after you log in?

**Comment by gvwilson** [comment]
Sure, but this one isn't required for launch - we can get through the 
first month with "click to go home / click on a link".

**Comment by wking** [comment]
On Wed, Feb 18, 2015 at 12:00:36PM -0800, Greg Wilson wrote:
> Sure, but this one isn't required for launch…

I'm not sure how the “essential” label squares with “isn't required
for launch”.  See also my previous confusion with “essential” + “v1.1”
for #170 [1].  I'd recommend dropping the “essential” and “defer”
labels in favor of assigning issues to milestones, because that gives
you more granularity on priority without diluting the other labels.

[1]: https://github.com/swcarpentry/amy/issues/170#issuecomment-74915443

**Comment by pbanaszkiewicz** [comment]
#221 was merged so I'm closing this issue.
