### ISSUE TITLE
Recording people who are interested in our activities

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#202]
In [this email thread](http://lists.software-carpentry.org/pipermail/amy_lists.software-carpentry.org/2015-February/000060.html), one of the admins asked for "a way to record people who noted interest in our activities, be that for a specific workshop or for Software Carpentry in general."  The details are:

> For clarity, we happen to receive enquiries of someone asking to attend workshop X. Sometimes the answer is yes, and they end to be recorded via the workshop attendees list. Other times, it isn’t possible to get them a place but we are interested in keeping in touch for future workshops / collaborations. The problem is that without a system, their enquiries can easily be forgotten in our archives.
> 
> Therefore, it would be handy if Amy could keep track of these enquiries, maybe recording:
> -   Name
> -   Email address
> -   Workshop for which they enquired / reason for which they inquired.

Note that this _isn't_ waitlisting people for a particular workshop, but rather keeping track of people who would (for example) like to attend a workshop somewhere near Buenos Aires (or wherever).  More precisely:

> -   People who learn about an upcoming workshop, would like to attend but cannot get a place: it’s our (SWC) concern to cultivate their interest and direct them towards other suitable workshops.
> -   People who wish to be helpers: again, it’s our concern to record their interest and arrange a helping place when possible.
> -   People who ask to be informed on the activities of Software Carpentry (workshops, instructors training, other activities): as well as directing these to the software-carpentry.org, we might also want to ping them directly about certain activities which we consider suitable to them.
>   The first two cases are by far the most significant, in my opinion, and we could also forget about the general type of enquiry for the time being.

**Comment by wking** [comment]
On Thu, Feb 26, 2015 at 05:11:44AM -0800, Greg Wilson wrote:
> In this email thread, one of the admins asked for "a way to record
> people who noted interest in our activities, be that for a specific
> workshop or for Software Carpentry in general."

How does my proposed modeling sound [1]?

> > For clarity, we happen to receive enquiries of someone asking to
> > attend workshop X. Sometimes the answer is yes, and they end to be
> > recorded via the workshop attendees list. Other times, it isn’t
> > possible to get them a place but we are interested in keeping in
> > touch for future workshops / collaborations. …
> 
> Note that this *isn't* waitlisting people for a particular workshop,
> but rather keeping track of people who would (for example) like to
> attend a workshop somewhere near Buenos Aires (or wherever).

I'm not clear on the distinction between “someone asking to attend
workshop X… [but] it isn’t possible to get them a place” and
“waitlisting”, maybe you can clarify it for me?  In any event, I think
we could represent this particular case with either a waitlisted role
or a FutureTask entry for that person as a student.  Since we have the
other use-cases as well (e.g. “I'd like to help out in the area”, “I'd
like to teach in the area”, …) it's probably best to stick to
FutureTask for all the cases.

As I mentioned in my email [1], my proposed logic needs Site.latitude
and Site.longitude, which is tied in with #6 and #120.

[1]: http://lists.software-carpentry.org/pipermail/amy_lists.software-carpentry.org/2015-February/000064.html

**Comment by gvwilson** [comment]
I think we're unlikely to actually input this information - @amyrbrown @gperu do you think you would?
