### ISSUE TITLE
Create checklist for event

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#21]
The event details page should either:

*  link to the Google Docs spreadsheet being used as a checklist for the event, or
* host the checklist itself.

In the former case, there should be a single-button way to create the required doc if it doesn't exist, and a single-button way to send the link to the event's instructors and hosts.  The latter design would have fewer moving parts, but would mean giving instructors and hosts access to the application.

**Comment by amyrbrown** [comment]
Do any admins use the Google checklists? I haven't been lately.

If we do house checklists on AMY (which would be my preference for usability) we'd want to associate checklist items with particular admins, and (ideally) show the user a list of all their open checklist items in one place (rather than having them only visible on Event pages).

Too feature-creepy?

**Comment by gvwilson** [comment]
I don't think anyone's using the Google checklists...

**Comment by pbanaszkiewicz** [comment]
Replaced with TODOS in #561.
