### ISSUE TITLE
Need a 'notes' field on Award

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#301]
I'd like to create a new badge called 'maintainer' to give credit to topic maintainers. When awarding it, I need to add a note saying when they were a maintainer.  I don't (yet) need notes on other kinds of awards, but might some day; since I don't know what those notes might be, adding a 'from/to' date pair is premature.

**Comment by wking** [comment]
On Sun, May 24, 2015 at 03:07:52PM -0700, Greg Wilson wrote:
> I'd like to create a new badge called 'maintainer' to give credit to
> topic maintainers.

Hmm.  While I get the “track everything in one place” driver, I think
we should try and keep clear boundaries about what Amy is for.  At the
moment, it's for tracking and planning events, which pulls in tracking
instructors (who are students at training events and instructors at
other events), sites, hosts, etc.  Amy is currently not about:

* Accounting.  We don't track payments, and that's hard to get right.
* Registration.  We use Eventbrite for this, since it's another hard
  problem and is only loosely bound to a SWC admin's side of event
  planning.
* Anything to do with lesson maintenance.  This is also loosely bound
  to event planning.
* Tracking installation issues, which splits out well into an external
  aggregator (numfocus/gsoc#3).
* Tracking which lesson material is used to teach a given topic at an
  event.  It's better to just keep this in the event website
  (wking/swc-setup-installation-test#2).

On the other hand, Amy probably *is* about which topics were or will
be taught at a given event (but not which *lessons* are used to teach
those topics).  This would help with matching up instructors (and we
already track instructor skills).

So if we're keeping Amy focused on the event-planner role, how do we
integrate with folks who also manage maintainer badging (since
@gvwilson is currently working in both capacities)?  Can we pull out
the badger to a separate application that pulls event-completion and
personal information from Amy?  It could pull maintainer information
directly from the lesson repository READMEs (since
swcarpentry/lesson-template#195).  And it could pull the list of
lessons from our lessons list [1].  Scraping GitHub IDs from a
“Maintainers” section in the READMEs wouldn't be difficult, but I'd be
in favor of a single file listing lesson repositories so we don't have
to scrape lessons.html.  Anyhow, an app that reached into those
canonical information sources and spit out badges makes sense to me
(hooray DRY), and doesn't sound like something that fits naturally
into the existing workshops application.  But I'd be fine with it
landing in a separate Django application that we also served from the
Amy project.  Serving several SWC apps under
amy.software-carpentry.org would also help us draw a clearer
distinction between the workshops app and the Amy project (see #247).

[1]: https://github.com/swcarpentry/site/blob/master/lessons.html

**Comment by gvwilson** [comment]
Doesn't seem to be much demand.
