### ISSUE TITLE
Format dates as YYYY-MM-DD everywhere

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#306]
All dates should always be shown in YYYY-MM-DD.  Is there an easy way to abstract this in Django (i.e., to put the date format in a variable or something that every template can reference)?

**Comment by wking** [comment]
On Wed, May 27, 2015 at 10:42:17AM -0700, Greg Wilson wrote:
> All dates should always be shown in YYYY-MM-DD.  Is there an easy
> way to abstract this in Django (i.e., to put the date format in a
> variable or something that every template can reference)?

You could add a setting for that and then write a context-injector to
expose it to the templates.  But I think it's easier to just hard-code
YYYY-MM-DD wherever you would have used that variable, because there's
no reason to format dates any other way.

**Comment by gvwilson** [comment]
Agreed - for now, add to the README.md ?  We'll eventually have dev 
guidelines, but eventually...

**Comment by wking** [comment]
On Wed, May 27, 2015 at 11:36:15AM -0700, Greg Wilson wrote:
> Agreed - for now, add to the README.md ?  We'll eventually have dev
> guidelines, but eventually...

I think the contributor-oriented CONTRIBUTING.md is a better fit than
the user-oriented README.md.  I'm also fine leaving this knowledge
undocumented and just having the maintainer comment on it when
reviewing PRs by contributors who aren't aware of the policy (since
the contributor list is likely to be you, me, and Piotr for the
foreseeable future ;).

**Comment by pbanaszkiewicz** [comment]
Ref #108.

**Comment by gvwilson** [comment]
Agreed - I'll add it to CONTRIBUTING.md

**Comment by pbanaszkiewicz** [comment]
Ref #314.
