### ISSUE TITLE
Repeated skill "Matlab"

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#348]
We can see it on `Find instructors` page: there's `MATLAB` and `Matlab`.

To get rid of it we probably have to write a migration.

**Comment by gvwilson** [comment]
We're going to change the skills to map to particular lessons - see the 
bottom of 
https://docs.google.com/forms/d/1NA2z3mXnrz4ZfEV02rk6vwdK4M180_sYpVjUQBt-yMc/viewform 
for what we'll get in the spreadsheet, so yeah, a migration...

**Comment by pbanaszkiewicz** [comment]
Okay, so we change Skill model, too?
To distinguish between different "variations" of the same skill ("The Unix Shell" vs "The Shell for Ecologists", "Programming with Python" vs "Python for Ecologists"). Or maybe we want to distinguish skills by software and then application (ie. "Matlab" — "control theory", and "Matlab" — "eletrical engineering", "Python" — "programming", and "Python" — "for ecologists")?

Do we want to distinguish between skills for DC and SwC lessons?

**Comment by gvwilson** [comment]
Nope - we might change the name of the model from 'Skill' to 'Lesson', 
but then it's just an enumeration of lessons we have - we stop trying to 
track "Hey, I know Python at level X" because that's hard to normalize.

**Comment by wking** [comment]
On Sun, Jun 07, 2015 at 03:54:50PM -0700, Greg Wilson wrote:
> Nope - we might change the name of the model from 'Skill' to
> 'Lesson', but then it's just an enumeration of lessons we have - we
> stop trying to track "Hey, I know Python at level X" because that's
> hard to normalize.

Hmm.  I can't tell if this is going to make it harder to track domains
as skills or not (see [1]).  What happens when we don't have a
domain-specific version of a lesson?  Do we care if a non-ecologist is
teaching the generic novice-Git lesson to a bunch of ecologists?
Would we be looking for an ecologist to teach that lesson?  Do we
intend to have a domain-specific novice-git-ecology lesson in the
future?

Personally, I'm fine leaving the binding loose here, since the sorts
of carpentry-level material we target don't have a large depth span.
Do we have examples of multiple lessons in an existing skill where we
have instructors who are competent to teach the basic lesson but not
the intermediate lesson?  If we're cutting instructor competence that
close frequently enough to encode it in AMY, I'd rather just tighten
down on skill assignment and shift instructors back to their
high-competence subjects until they've had more time to upskill their
just-past-novice-competence subjects.

[1]: https://github.com/swcarpentry/amy/issues/342#issuecomment-109485888

**Comment by gvwilson** [comment]
Will be fixed by #360.

**Comment by pbanaszkiewicz** [comment]
Shifting to v0.5 since #374 is scheduled for v0.5.
