### ISSUE TITLE
Crash when importing existing event

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#427]
1.  Copy AMY db to desktop.
2.  Run local server.
3.  Create new event.
4.  Import from `http://dgasmith.github.io/2015-08-24-stanford/`. (Note: this event is already in the database.)
5.  Crash.

**Comment by pbanaszkiewicz** [comment]
@gvwilson I assume this happens with the code from #426?

**Comment by pbanaszkiewicz** [comment]
If that's the case, the error happens because `Event.slug` doesn't have the unique constraint.

So we're able to add more events with the same slug. The error appears when getting one particular event by it's slug: we can't because there are more than 1.

Proposed solutions:
1. Make `Event.slug` unique, or
2. implement #259

**Comment by gvwilson** [comment]
Yup, this is with #426.
>
> If that's the case, the error happens because |Event.slug| doesn't 
> have the unique constraint.
>
> So we're able to add more events with the same slug.
>

Right, so before trying to add, we should 'get' to see if that slug 
already exists and reject the new Event if so, yes?
Thanks,
Greg

**Comment by pbanaszkiewicz** [comment]
@gvwilson this can be done automatically if we use ModelForm and set `unique=True` to `Event.slug` or we can extend our existing `clean` method on that ModelForm to check for the unique constraints.

I'd opt for the 1. option.

**Comment by gvwilson** [comment]
I trust your judgment.
Thanks,
Greg
