### ISSUE TITLE
Export public information about workshops over HTTPS

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/amy#432]
Talking with @gvwilson he mention that we should revamp the build stack of Software Carpentry [website](https://github.com/swcarpentry/site) to take advantage from AMY, i.e. let AMY create part of `_config.yml` of https://github.com/swcarpentry/site that currently is

- [x] airports (**we should drop the name of instructors**)
- [x] badges
- [x] workshops

For workshops we currently have

- country
- enddate
- humandate
- instructor
- latlng
- layout
- registration
- slug
- startdate
- url
- user
- venue

and I think that we only need

- country
- startdate
- enddate
- latlng
- slug
- url
- venue

We can generate the `humandate` from `startdate` and `enddate`. The others fields can be drop without problem.

The `Event` model only have

- site
- tags
- organizer
- start
- end
- slug
- url
- reg_key
- attendance
- admin_fee
- invoiced
- notes

so we will need to add

- country
- latlng
- venue

@pbanaszkiewicz Did I miss some technical detail?

@gvwilson Did I miss something? Should we continue on this?

**Comment by r-gaia-cs** [comment]
I forgot to mention that we can reuse `workshops/management/commands`.

**Comment by pbanaszkiewicz** [comment]
Thanks a lot, Raniere, for getting this issue up. I don't think I'd assemble such a complete list.

Question: why are we going to drop the name 'instructors'? Is this only on the presentation layer of SwC webpage?

Notice: we have a really hard time figuring out the venue/site data correctly. There's a lot of misinterpretation within the database, and I'd like to [have a discussion](https://github.com/swcarpentry/amy/issues/5#issuecomment-122214844) with all admins regarding event and host location representation.

I'm bringing this topic up because:
1. we don't store venue data for an event
2. I'm not sure if event's site's country would be correct in all cases
3. we don't store lat/long data for sites, I believe

Easiest solution to this issue ("Export public information about workshops…") would be to return only a list of URLs so that the `make` could then iterate through them and gather all information from their websites.

Ideal solution would be for AMY to became a central database of all events. But we need to solve some issues first (e.g. #5 #120 #6).

**Comment by r-gaia-cs** [comment]
> Question: why are we going to drop the name 'instructors'? Is this only on the presentation layer of SwC webpage?

To generate the website we don't need the name of instructors that taught at workshop XXX. I believe that some instructors could have some reasons for that information not be public available and those that want their names linked the workshops they taught could do it in many different ways.

> Easiest solution to this issue ("Export public information about workshops…") would be to return only a list of URLs so that the make could then iterate through them and gather all information from their websites.
>
> Ideal solution would be for AMY to became a central database of all events. But we need to solve some issues first (e.g. #5 #120 #6).

@gvwilson I will postponed work on this a little so we have time to talk (maybe Monday).

**Comment by gvwilson** [comment]
On 2015-07-18 12:11 AM, Raniere Silva wrote:
>
>     Question: why are we going to drop the name 'instructors'? Is this
>     only on the presentation layer of SwC webpage?
>
> To generate the website we don't need the name of instructors that 
> taught at workshop XXX. I believe that some instructors could have 
> some reasons for that information not be public available and those 
> that want their names linked the workshops they taught could do it in 
> many different ways.
>

Instructors don't mind their names being public - after all, they're on 
the workshop website - but we've just never bothered to list them on the 
main web site (not enough space).

>     Easiest solution to this issue ("Export public information about
>     workshops…") would be to return only a list of URLs so that the
>     make could then iterate through them and gather all information
>     from their websites.
>

-1 because:

1. Polling is slow (and subject to timeouts when GitHub is busy).
2. Some workshops don't have proper GitHub websites - we've loaded the 
required information into config/archived.yml so that they appear 
correct, and will do the same with the AMY database.
3. We can amend information in the AMY database to be "right" for 
workshops whose websites are wrong.

Thanks,
Greg

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by pbanaszkiewicz** [comment]
> -1 because:
> 
> 1. Polling is slow (and subject to timeouts when GitHub is busy).
> 2. Some workshops don't have proper GitHub websites - we've loaded the required information into config/archived.yml so that they appear correct, and will do the same with the AMY database.
> 3. We can amend information in the AMY database to be "right" for workshops whose websites are wrong.

Okay, in this case we need to enhance what AMY keeps in DB about events, because, as Raniere listed, we're lacking country, lat/long, venue.

**Comment by gvwilson** [comment]
Yup.

**Comment by gvwilson** [comment]
This should be the Big One for v0.8 - it'll let us cut a lot of stuff out of rebuilding the 'site' repository.

**Comment by pbanaszkiewicz** [comment]
Closing via #459 and #463.
