### ISSUE TITLE
Normalize workshop URLs

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#465]
Right now (2015-08-18), workshop URLs are being stored as:

* `https://github.com/user/yyyy-mm-dd-site` (my preferred format)
* `http://github.com/user/yyyy-mm-dd-site/` (`http` instead of `https`, and a trailing slash)
* `http://user.github.io/yyyy-mm-dd-site` (the GitHub Pages URL rather than the repository URL)

URLs should be normalized to simplify search and processing (e.g., for the main web site).

**Comment by pbanaszkiewicz** [comment]
The machinery in #467 provides us with `event.get_repository_url()` and `event.get_website_url()` methods.

If `event.url` is in one of recognized formats (either to repo or to website), these methods will provide the other URL.

So if `event.url` is `http://user.github.io/yyyy-mm-dd-site` the `event.get_repository_url()` will return `https://github.com/user/yyyy-mm-dd-site/` (we can drop the trailing slash if required), but `event.get_website_url` will return `event.url`.

We can change it so that:
1. `event.get_website_url` formats the `event.url` to `https://user.github.io/yyyy-mm-dd-site` even when `event.url` matches any other format for a website URL
2. `event.get_repository_url` formats the `event.url` to `https://github.com/user/yyyy-mm-dd-site` even when `event.url` matches any other format for a repository URL

One other option is to overwrite `event.url` upon save + force users to use specific format on input, but I'm against it because it requires migration of all existing events.

@gvwilson what do you think about this?

**Comment by gvwilson** [comment]
I think we should:

1. Store the normalized form.
2. Put up a great big warning on the "save" page telling people when 
we've changed what they typed in.
3. Migrate existing records - there shouldn't be that many left in the 
database that aren't normalized.

**Comment by pbanaszkiewicz** [comment]
If we want to enable workshop sites hosted outside of GitHub, we should:

1. Put all required variables into `<meta>` in workshop-template
2. Read from these `<meta>` tags instead of parsing `workshop/index.html` in workshop page validation
3. Use only workshop website URL in AMY, not repository URL

@gvwilson if you agree I could start working on this problem soon.

**Comment by gvwilson** [comment]
Please assign it to me for thinking, but it's a low priority for now.

**Comment by pbanaszkiewicz** [comment]
In case of https://amy.software-carpentry.org/workshops/event/2015-09-26-conestoga there was an error with validation function not discovering correct URL. It may need further investigation, but maybe we could rework whole URL and validation thing altogether…?

**Comment by gvwilson** [comment]
Proposal welcome :-)

**Comment by pbanaszkiewicz** [comment]
Postponing to v1.2 because I won't be able to finish it this month. #483 is taking much time.
