### ISSUE TITLE
Indicate "self-organized" for administrator of self organized workshops

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#484]
Right now AMY directs you to leave this field blank if self organized.
I'd like to see "self-organized" as one of the drop down options.  Later on, if I'm querying the database directly to find all self-organized workshops I'd rather write `SELECT * FROM events WHERE administrator = 'self-organized'` instead of `SELECT * FROM events WHERE administrator IS NULL`.

**Comment by pbanaszkiewicz** [comment]
@maneesha this is impossible to do this way. But there's another way.

We'd have to have 2 different fields because `events.administrator` is a relation and it has to be an integer type. Therefore there would have to be another field to indicate self-organized or not (== boolean type).

Is `SELECT * FROM events WHERE is_self_organized = 1` better than `SELECT * FROM events WHERE administrator IS NULL` for you, @maneesha?

**Comment by maneesha** [comment]
Sorry, I should have said my sample query was in pseudocode.  Really all I
meant was that to find self organized workshops I'd rather query by a value
than query for null.

**Comment by pbanaszkiewicz** [comment]
Why don't you like querying for NULL?

Semantically it makes sense to mark events without administrator (ie.
self-organized) with `administrator=NULL`.

If we added a host called "Self-organized" then you'd have to memorize it's
ID and you'd query by that ID:

SELECT * FROM events WHERE administrator = 1274

It's definitely more error-prone than querying for NULL values.

**Comment by maneesha** [comment]
My problem is in assuming NULL means self-organized.  Null could be the
result of an unknown administrator, or a user overlooking that field in
data entry.  That's why I'd like to have an actual value assigned to
self-organized.

**Comment by tracykteal** [comment]
I agree that assigning a value to 'self-organized' is better than using NULL. It does make sense that administrator=NULL when there's no administrator, but in this case 'no administrator' is still actually a value and not an absence of a value as NULL would indicate. I think assigning an integer value to 'self-organized' is fine. We can remember it, or have it in the notes.

**Comment by pbanaszkiewicz** [comment]
@maneesha @tracykteal is there *any* chance you can provide me with a list of events with no (or unknown) administrator? Or the list of self-organized events?

**Comment by pbanaszkiewicz** [comment]
@maneesha @tracykteal if you're unable to provide me with such list, I'll default to look for events with "self-organized" or "self organized" in their notes, or with "Not applicable since self-organized" as their invoice status.

I may extend the query with events with `admin_fee=0`, but there's over 300 of them so I'm not sure if this is correct.

**Comment by maneesha** [comment]
I can do this for SWC workshops from August 2015 on. 

I don't want to extend the query with `admin_fee = 0` because there are several reasons this may have been the case.

I have not gotten enough into DC yet so @tracykteal will have to help with this.

And all this is exactly why I wanted a value instead of `null` for self-organized and why I wanted all those options for invoice status.  Thanks for making this happen!

**Comment by tracykteal** [comment]
DC doesn't have any self-organized workshops. They've all been organized by me or Aleksandra.
