### ISSUE TITLE
Add location information to sites

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#5]
We indicate a person's (rough) location by listing the airport nearest her. We should also have some way to indicate the location of a host organization for a workshop. However, some sites don't have a location of their own, and others (e.g., the SSI) have multiple locations.

**Comment by amyrbrown** [comment]
+1 

I often google "nearest airport to Euphoric State University" when looking for instructors -- would be handy to have this information in AMY.

**Comment by pbanaszkiewicz** [comment]
I'd like to dedicate v0.7 for changes in database that will allow us to sort out the issues with site/host/organizer nomenclature and representation.

I will need to meet with admins to talk about that, because they're more knowledgeable than me.

I hope to send an email to admins later today.

**Comment by pbanaszkiewicz** [comment]
@amyrbrown currently the situation is:

The location is shifted from Host to Event.

So we set host on event to the organization that's considered to be the host of that event.

There are some hosts that have multiple locations (SSI, Elixir project, etc.), so instead of putting multiple locations into Hosts, I decided to store the location within events.

There are other reasons for putting locations within events, for example: with "Import from URL" we are able to fill out location fields automatically.

So to fix "nearest airport to Euphoric State University" issue I think I could:

1. add "nearest airport" to the event (don't like this solution, but well)
2. add "Find closest instructors" to event's detail page

or

1. add "Find closest instructors" to event's detail page (it'd use lat/long data of event's location, as opposed to "nearest airport")

@amyrbrown what do you think? If I didn't express myself clearly please let me know.

**Comment by amyrbrown** [comment]
Sounds good. I think if we are adding a "find closest instructors" link to events, we don't need to store the closest airport -- the only reason one needs to know the closest airport is to facilitate using the find-instructors functionality.

**Comment by pbanaszkiewicz** [comment]
Okay, in that case the "Find closest instructors" will use lat/long data for the event's location.
