### ISSUE TITLE
Add nickname/alternate name or notes field to Person records

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#500]
People may go by more than one name (obvious nicknames like Jonathan goes by Jon, but also less obvious nicknames, maiden/married names, Anglicized names, etc).

We should have a way that makes it easy (or at least easier) to track them.  Not sure what the best way to do this would be - suggestions?

**Comment by pbanaszkiewicz** [comment]
Oh, there was an ongoing argument between us, developers, about how we should keep track of names.

It's one of two ways:

1. Keep track of every alternative we may have (Greg likes that): formal way, informal, etc. etc. I remember Greg found 4 forms he wanted to see in AMY.
2. Don't keep track of anything, just use one field for a name (it could be "Piotr Banaszkiewicz", for example, instead of two separate fields for first and last name).

Truth is, developers worldwide prefer °2 because it's probably impossible (and certainly insane) to have a system that works good with all naming systems from all of the world.

So now AMY implements something that's good for like 30-50% (?) of population: first, middle, and last name.

Maybe @gvwilson wants to add something here.

**Comment by maneesha** [comment]
Yeah, I know this is complicated -- see
http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

I don't actually have a solution -- I don't think anyone in the world has a
real solution.  Maybe just have a notes field so I (and other admins) can
just enter in whatever notes help us keep track of who's who.

**Comment by gvwilson** [comment]
I'm happy to rewrite name handling so long as we can reliably sort 
people alphabetically by name - 'Jens von der Linden' comes before 'Greg 
Wilson'.

**Comment by pbanaszkiewicz** [comment]
Unless @maneesha hits this issue from time to time, we shouldn't worry. Otherwise, is there a consensus about name handling? Do we want more fields or less fields?

**Comment by maneesha** [comment]
I don't this has an easy solution and I don't think we need to prioritize this.

**Comment by chrismedrela** [comment]
I'm closing it since we have `Person.notes` field now.
