### ISSUE TITLE
Get attendance count from list of learners

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#508]
See https://amy.software-carpentry.org/workshops/event/2015-08-27-ualberta for example.  List of learners was imported into AMY but attendance count is still null.

Can we have something where attendance = null by default, can be updated by direct user input OR count(learners), whichever is greater.

(Also I've been interpreting attendance to be only learners, not helpers/instructors/etc)

**Comment by gvwilson** [comment]
Hi Maneesha,

1. You're correct, attendance should be just learners, not instructors 
and helpers as well.  Sometimes the total reported for a workshop will 
differ from the headcount in the attendance list because people choose 
not to be listed (e.g., we get a total of 30 from the organizer, and 
only 10 names are on the sign-up sheet).

2. How about adding to the problem report page so that if attendance == 
0 *and* there are people listed as learners, it's flagged?

Thanks,
Greg

**Comment by maneesha** [comment]
What would make more sense to me is something like (pseudocode):

```
attendance = null      # to start
attendance = user_input    #at any time
if attendance < count(learners): attendance = count(learners)
```

So attendance starts off null.  It can take user input at any time.  If the count of learners is ever greater than what's in that field, that field is updated to count of learners.  This condition is to be evaluated only when new learners are added.  The value for attendance should never be less than the count(learners).

So if I got 10 names, attendance should automatically be 10.  If I then find out 30 people actually attended, i can manually update that to 30.

**Comment by pbanaszkiewicz** [comment]
> So if I got 10 names, attendance should automatically be 10. If I then find out 30 people actually attended, i can manually update that to 30.

Sounds reasonable to me. Let me look for how and where to implement this.
