### ISSUE TITLE
Possible to send out reminder emails to instructors that will be teaching?

### ISSUE THREAD

**Issue by karinlag** [swcarpentry/amy#516]
I just noticed in the Steering Committee minutes a suggestion that AMY might be able to send out reminder emails to instructors who will be teaching, to avoid calendar mishaps. In that connection I was wondering if we could create/attach an ics file to the email? In that case, we could also skip the "entering wrong data" mishap.

**Comment by pbanaszkiewicz** [comment]
@karinlag so just to be clear: you're suggesting that we send out ICS with workshop's dates marked as some event? So that instructors can easily add the event to their calendars?

ref. #51.

**Comment by karinlag** [comment]
On 10/5/2015 12:09 PM, Piotr Banaszkiewicz wrote:
> @karinlag <https://github.com/karinlag> so just to be clear: you're
> suggesting that we send out ICS with workshop's dates marked as some
> event? So that instructors can easily add the event to their calendars?

Yes, exactly. That way we can help people not write the wrong date in 
their calendars. I am however uncertain whether this one should be sent 
out right after the workshop has been created, or at a set time before 
the workshop (like for instance a month before).

Karin

**Comment by maneesha** [comment]
I'm not sure about this.  
I'm in regular contact with instructors & hosts in the weeks leading up to a workshop and I worry this will be just one more email that clutters people's inboxes.

We had just one case of an instructor who didn't show up because of a date mixup (right when I started so I wasn't involved in the planning of this at all).  The host & I both emailed her several times over a week or so and she never responded to those emails so I don't think an automated calendar reminder would have helped.  Someone who doesn't look at numerous personal emails is unlikely to look at an automated email. 

I've only been doing this for a couple of months... has this been a bigger problem?

**Comment by karinlag** [comment]
On 06/10/15 16:30, maneesha sane wrote:
> I'm not sure about this.
>
> I'm in regular contact with instructors & hosts in the weeks leading up
> to a workshop and I worry this will be just one more email that clutters
> people's inboxes.
>
> We had just one case of an instructor who didn't show up because of a
> date mixup (right when I started so I wasn't involved in the planning of
> this at all). The host & I both emailed her several times over a week or
> so and she never responded to those emails so I don't think an automated
> calendar reminder would have helped. Someone who doesn't look at
> numerous personal emails is unlikely to look at an automated email.
>
> I've only been doing this for a couple of months... has this been a
> bigger problem?

Not a big problem no, but I know that for myself, I sometimes worry if I 
actually get things in on the correct date (but that might just be me).

How about an in between thing: we send out a "registration" kind of 
email, once we have an instructor for a workshop, with an attached ics 
that contains the dates and the address? In that case it would work more 
as a courtesy thing, as well as us ensuring that we and the instructors 
have the correct info.

Karin

**Comment by gvwilson** [comment]
Instead of sending reminders to instructors, how about we send reminders to execdir@ or some other small list for a couple of months and see how we feel?

1. I always meant to send "good luck!" and "how did it go?" messages to instructors before and after, but forgot.
2. It'll help us shake out bugs in email sending.
3. If we find it annoying, odds are instructors will too.

**Comment by jduckles** [comment]
+1, I like the idea of being reminded when a workshop is kicking off.

**Comment by maneesha** [comment]
I've just started sending personal "Are you ready? Good luck" emails a few days before the workshop.
For a while now I've been sending personal "How'd it go?" emails a few days after the workshop.  

We could automate this but there are often details I'll share or ask about that are custom to each workshop.

**Comment by karinlag** [comment]
On 09/10/15 18:53, maneesha sane wrote:
> I've just started sending personal "Are you ready? Good luck" emails a
> few days before the workshop.
> For a while now I've been sending personal "How'd it go?" emails a few
> days after the workshop.
>
> We could automate this but there are often details I'll share or ask
> about that are custom to each workshop.

While I I love the personal touch, the neurotic in me would love to know 
that somebody else(TM) has already or will send me a reminder that I can 
put directly into the calendar, so that _I_ will not be the reason for 
the screw up if and when :)

Karin

**Comment by pbanaszkiewicz** [comment]
We can automate sending "Event's calendar" emails, and leave all personal emails to Executive Directors and/or Maneesha.

**Comment by pbanaszkiewicz** [comment]
@maneesha @karinlag @jduckles @gvwilson anyone can use their deciding voice and tell me who should be emailed about what and when? I'll appreciate it a lot :-)

Another thought just stroke me: we could perhaps use #483 for https://github.com/swcarpentry/amy/issues/516#issuecomment-146929035 (e.g. admin comes to event's details page and sees they should send "Good luck" email today).

**Comment by karinlag** [comment]
On 14.10.2015 21:28, Piotr Banaszkiewicz wrote:
> @maneesha <https://github.com/maneesha> @karinlag
> <https://github.com/karinlag> @jduckles <https://github.com/jduckles>
> @gvwilson <https://github.com/gvwilson> anyone can use their deciding
> voice and tell me who should be emailed about what and when? I'll
> appreciate it a lot :-)

I nominate @jduckles and @gvwilson as the ultimate decision makers here.

K

**Comment by gvwilson** [comment]
Not me! @jduckles and @maneesha

**Comment by jduckles** [comment]
@maneesha up to you on this one. You're in the thick of how this actually would work/not work.

**Comment by maneesha** [comment]
I wasn't sure about having automated emails go out because I know I would ignore something that looked like an automated email - I think a lot of other people would, too.  However, I do send basically the same "Are you ready?" and "How'd it go?" emails to hosts/organizers/instructors before & after the workshop.  I have fill-in-the-blank templates that I use.  

How about this... now that we have admins assigned to specific workshops can we have  emails that go out that look like they're coming from me (or that workshop's assigned admin)? I'll share the fill-in-the-blank template that I use for each.

**Comment by karinlag** [comment]
On 12/5/2015 10:14 PM, maneesha sane wrote:
> I wasn't sure about having automated emails go out because I know I
> would ignore something that looked like an automated email - I think a
> lot of other people would, too. However, I do send basically the same
> "Are you ready?" and "How'd it go?" emails to
> hosts/organizers/instructors before & after the workshop. I have
> fill-in-the-blank templates that I use.
>
> How about this... now that we have admins assigned to specific workshops
> can we have emails that go out that look like they're coming from me (or
> that workshop's assigned admin)? I'll share the fill-in-the-blank
> template that I use for each.

+1 from me.

K

**Comment by pbanaszkiewicz** [comment]
@maneesha I'm not sure if we can send emails on someone else's behalf – I mean: can we send emails from our server and use "From: giacomo@software.uk" header to indicate that it was Giacomo who sent that email? If I was the recipient's server, I'd put that to spam.

@wking do you have any experience with such stuff?

**Comment by jduckles** [comment]
As long as the reply-to is @software-carpentry.org we can send the messages through the mail.software-carpentry.org SMTP server I'd think.

**Comment by gvwilson** [comment]
See #795.
