### ISSUE TITLE
Post-workshop head-count form on AMY for instructors

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#554]
Can/should we add a simple form on AMY (like the instructor details form) to collect head count for workshops once they're done?  And maybe tick off the lessons that were actually taught?  I know this is all supposed to be in the post-workshop survey for instructors, but maybe having an AMY-based form would increase fill-in rates.

**Comment by jduckles** [comment]
Is it too much to have learners, check-in by name & optional email on an AMY form. The URL can use the slug of the workshop.  Something like: https://amy.software-carpentry.org/checkin/2015-xx-xx-xxxx

A dashboard view for the instructor (showing the total) would help them to nudge folks who didn't sign in to do so. I think we can also have the instructor submit a headcount.  Gathering the info in two ways will be informative about the response rates. Is that too much to ask you think?

The hard part is passing the info along to instructors and getting them to use it...but we could add the link to the workshop page, maybe only have it submittable on the day(s) of the workshop.

**Comment by pbanaszkiewicz** [comment]
@gvwilson @jduckles @maneesha still thinking about this way of collecting attendance data?

**Comment by jduckles** [comment]
@maneesha what are your thoughts? Would this be helpful?

**Comment by pbanaszkiewicz** [comment]
@maneesha: awaiting feedback on this topic. Thanks!

**Comment by maneesha** [comment]
I agree with @jduckles  that no matter what system we have the hard part will be having instructors do it.

For workshops that use Eventbrite, I believe Eventbrite has a checkin button.  @pbanaszkiewicz If we get instructors to make learners checkin on Eventbrite can we import that straight into AMY?  You know the Eventbrite API better than me.

If we don't or can't use Eventbrite then something built into AMY would work.

Also if we do something like this I'd actually really like to see this for both days of the workshop.  We often see attrition from registration to day 1 to day 2 and I'd like to track that.

Other than that the only problem I see with this is that many hosts don't share names/emails of learners for privacy reasons.

**Comment by pbanaszkiewicz** [comment]
### Eventbrite API

@maneesha: unfortunately there is no public Eventbrite API allowing developers to check in people (http://stackoverflow.com/a/19446732). I found out that Eventbrite allows event managers to use their own Eventbrite Neon application to check people in on entry, so they must have a private API for that.

With the API we're able to get people checked-in, though: https://www.eventbrite.com/developer/v3/formats/attendee/#ebapi-attendee-barcodes

### Check-in button

@maneesha:
> For workshops that use Eventbrite, I believe Eventbrite has a checkin button.

Do you know for sure and if so is the button available for attendees as well, not only to event managers (via Eventbrite Neon)?

### AMY form

If we decide to do AMY form, here's what I'm thinking about:

1. AMY hosts a "Check-in form" under `https://amy.software-carpentry.org/workshops/check-in/{slug}`, with `name`, `last_name`, `email` (all optional) fields. Additionally the form saves creation date to match with event's timespan
2. A cookie is stored in every respondent's browser, so that re-entry of `https://amy.software-carpentry.org/workshops/check-in/{slug}` doesn't ask user for details again.
3. Form entries are gathered and available for verification by admins.
4. Verified entries can be added as Person records.

There are some challenges ahead:

1. We would probably have to move to timezone-aware dates/datetimes.
2. The way `Event.attendance` is used across AMY would have to change.

**Comment by maneesha** [comment]
The Check in button is available to organizers via the web interface.  Neon app is not necessary.  It does not seem to be available to attendees.  

If we build check in feature in to AMY I would like to have checkin by day.  Most workshops see at least a small drop off on day 2 and if we're going to build this feature, I would like to track that.

**Comment by pbanaszkiewicz** [comment]
I had an idea a few hours ago about that check-in form, so let me drop it here. Maybe we can encourage learners to check in at the end of second days and feed their data to our certificate script (assuming I'll get #343 and #656 to work) so that they'd get certificates of attendance?

**Comment by gvwilson** [comment]
:+1: provided #656 happens first.

**Comment by jduckles** [comment]
I like it!

**Comment by gvwilson** [comment]
If we're opening up AMY to instructors anyway (so that they can update their info), this starts to look more reasonable... ?

**Comment by maneesha** [comment]
And if we are thinking about this I really want to push for daily attendance - see https://github.com/swcarpentry/amy/issues/514
where we've talked about it and I've noted that I've been tracking it myself.
