### ISSUE TITLE
Alert for recently changed github pages

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#562]
This is an issue more for self organized workshops than traditional ones.
Sometimes a workshop's instructors change.  The organizers make the change on the github page but don't necessarily tell me.  Since I don't know I can't then make the change in instructors in AMY.

So when the workshop is over, the right people are not invited to the debriefing session.  And then long term we don't have accurate records on who taught what.

Can we have an alert in AMY for recently changed github pages?  Maybe something that runs once a week or so?

**Comment by jduckles** [comment]
How about just using the `.atom` feed of the github pages branch of the repo? They can't change anything on the page without committing it 😁.
.
For example:
`https://github.com/swcarpentry/site/commits/master.atom` shows the latest activities on the `swcarpentry/site` repo for the master branch?  We'd need to do it for the `gh-pages` branch of the workshop's repos, but then it could flag pages changed in within 3-5 days based on the atom data.

**Comment by pbanaszkiewicz** [comment]
Thanks @jduckles for your suggestion, it's probably the only feasible way to do this.

Unfortunately running such thing every week or so requires additional infrastructure (== more work) so I schedule this issue for v1.3.

**Comment by jduckles** [comment]
You could push the atom call to client side JS. Use the clients "infrastructure". Agreed though, not super high priority, just a "that would be nice" feature.

**Comment by wking** [comment]
I'm happy to take a stab at this, but I have a few questions:

1. Do we require a GitHub repository based off
   swcarpentry/workshop-template, or do we allow events with just a
   website URL that embeds meta tags on the homepage like what
   swcarpentry/workshop-template gives you?  This is related to #465.

2. Do we have a reliable way to map instructor names from the YAML or
   meta tags to AMY people?  This may be related to #526.  One
   potential workaround is to allow AMY IDs, GitHub usernames, or
   known-to-AMY email addresses as more reliable identifiers in the
   event webpage's instructor list.

Once we have those, having a nightly poll of events that will happen
in the next two months is feasable, and I don't see a need to go
through an Atom feed when we can just re-parse the original data
source and check for differences (which would also allow us to support
sites that don't have an associated repository with an Atom feed).

**Comment by pbanaszkiewicz** [comment]
Hello @wking! Long time no see.

1. We always want the workshop website to be GH repository fork of @swcarpentry/workshop-template.
2. After #465 is implemented we'll still want folks to fork workshop-template since it's easier than explaining HTML meta tags to them. However, the AMY-part of #465 will allow to validate tags on any website.
3. The only form of matching instructors & helpers is human intelligence - the "Import/Update from URL" feature simply adds the names to the `notes` field.
4. #526 is related to bulk upload only (where "name→person" matching happens).
5. As far as I know, the number of workshop websites not hosted on GitHub is insignificant (@maneesha can you correct me on that if I'm wrong?).

Here's how I thought about implementing this issue:

1. Store last commit ID (or modification date) within `Event` object, compare with the feed and display a message if they differ
2. Store `instructor` and `helper` tags contents within `Event` object, compare with the tags in the website (after #465 is merged) and display a message if they differ

The comparison would take place upon entering the event details page (AJAX wouldn't work because foreign domain policy?). The displayed message would suggest admin to update the event with "Update from URL" feature (which would not match "name→person" because it doesn't).

**Comment by wking** [comment]
On Sat, Nov 07, 2015 at 01:49:53PM -0800, Piotr Banaszkiewicz wrote:
> Hello @wking! Long time no see.

Yeah, sorry about that :p.  Looks like things have been going well
here though :).

> 2. After #465 is implemented we'll still want folks to fork
>    workshop-template since it's easier than explaining HTML meta
>    tags to them. However, the AMY-part of #465 will allow to
>    validate tags on any website.
> …
> 5. As far as I know, the number of workshop websites not hosted on
>    GitHub is insignificant (@maneesha can you correct me on that if
>    I'm wrong?).

These both sound reasonable to me.  I think there's an argument to be
made for flexibility and not binding our workflow too tightly to a
specific vendor, but if nobody is actually supplying non-GitHub sites,
then we can certainly punt on that for now.

> Here's how I thought about implementing this issue:
> 
> 1. Store last commit ID (or modification date) within `Event`
>    object, compare with the feed and display a message if they
>    differ

This will likely have lots of false positives, as folks edit portions
of their event page that aren't reflected in AMY.

> 2. Store `instructor` and `helper` tags contents within `Event`
>    object, compare with the tags in the website (after #465 is
>    merged) and display a message if they differ

This sounds better to me, but see below…

> The comparison would take place upon entering the event details page
> (AJAX wouldn't work because foreign domain policy?).

I don't think CORS is a concern here, since the current page
comparison is happening in AMY (via the event_import endpoint for
manual triggers), so AMY can access any public page and then display
that information to the admin (instead of having the user agent trying
to access the possibly un-CORSed website via AMY-hosted JavaScript,
which wouldn't work).

> The displayed message would suggest admin to update the event with
> "Update from URL" feature (which would not match "name→person"
> because it doesn't).

So the plan is to convert workshops.util.parse_tags_from_event_index
to just use the YAML header parsing from workshops.check.check_file,
and then:

1. Add Event.upstream and Event.reviewed strings in a migration.

2. Nightly job checks next two months of events.  For each event:
   a. Use workshops.util.parse_tags_from_event_index to extract the
      current metadata from their gh-pages tip.
   b. Compare metadata from that header with what we have stored in
      AMY.
   c. Set a new Event.upstream string with content of the YAML header
      that we can't automatically compare (e.g. instructor/helper
      names) or where we can automatically compare with an AMY field
      and the values don't match (e.g. start dates).
   d. If Event.upstream ≠ Event.reviewed, email an admin?  All admins?
      It looks like we've had mail handling since 830685f8, #476.

3. When an admin hits /workshops/events/, there will be a new column
   for “changed”, which would only be set when Event.upstream ≠
   Event.reviewed.  You can mouse-over to get keys from the
   Event.upstream YAML.  Entering the event-detail or -edit pages
   would show a new row with the Event.upstream YAML, maybe with a
   diff between it an Event.reviewed?

4. From the event-edit page, the admin can either hit the “Update from
   URL” button or edit the fields by hand.  When they feel they have
   adjusted AMY to reflect the new upstream information, they hit a
   new “Set reviewed” button to copy the upstream YAML into the form
   field for reviewed YAML.  Once they save the event, future upstream
   fetches will show upstream YAML either matching AMY data or showing
   up in the reviewed YAML, so no further alerts are triggered until
   upstream makes a change that is neither in an automatically
   comparable AMY field or in the reviewed YAML.

This becomes easier as we reduce the number of fields that we cannot
compare automatically.  From the current workshop-template YAML front
matter [1], we can compare venue, address, country, latlng, startdate,
enddate, contact, and eventbrite directly.  We don't currently care
about language (although we ask about it in EventRequest), humandate,
humantime, or etherpad.  The only fields we can't reliably compare are
instructor and helper.  By replacing the current YAML list of strings
in both cases with a list of maps:

  instructor:
    - name: W. Trevor King
      github: wking
    - name: Greg Wilson
      twitter: gvwilson
    …

we can automatically lookup people in AMY using the more reliable
GitHub / Twitter / URL / email identifiers.  And folks who for some
reason do not want to expose *any* of those fields can just use:

  instructor:
    - name: W. Trevor King
    - name: Greg Wilson
    …

and have what we have now (with manual admin-side name matching).  To
incentivize event maintainers to add the metadata independent of AMY,
we could adjust the template to add links to the instructor's GitHub
account / Twitter account / homepage / mailto-email.

[1]: https://github.com/swcarpentry/workshop-template/blob/bc06ef4275dc8b29a32be76a4076362f01d7df5b/index.html#L4-L17
