### ISSUE TITLE
More enumeration values for invoicing status

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#587]
1.  "not invoiced for historical reasons" (because some workshops took place before we started charging)
2.  "not invoiced because of partnership" (which will cover many train-the-trainer events).

@maneesha can you think of others?

**Comment by maneesha** [comment]
Yes, I've wanted to put in a similar issue myself - we should have had option 2 on the list all along (see #469) although I'd call it "Not invoiced because of membership" as both partners and affiliates may not pay fees.

One other situation I've seen come up is that the entire fee was covered by student registration fees but I have marked that as "other arrangements made"  -- they paid via Eventbrite rather than paying an invoice.  If registration fees only covered a portion of the admin fee, they still get an invoice for the difference.

**Comment by pbanaszkiewicz** [comment]
@gvwilson @maneesha do you want it for December release?

**Comment by gvwilson** [comment]
Yes please.

**Comment by pbanaszkiewicz** [comment]
@gvwilson and @maneesha:

I plan to add 'not invoiced for historical reasons' for all events with unknown invoice status older than 2014. I also plan on marking them as 'completed' so they won't bother admins anymore. Any objections?

@maneesha I'm sorry that 'Not applicable because partner organization' was not included in the solution for #469, I don't know how that have happened.

**Comment by gvwilson** [comment]
> I plan to add 'not invoiced for historical reasons' for all events 
> with unknown invoice status older than 2014. I also plan on marking 
> them as 'completed' so they won't bother admins anymore. Any objections?
+1
