### ISSUE TITLE
Strip spaces from personal/middle/family names during import

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#612]
I just removed leading and trailing spaces from the personal, middle, and family names of about 50 people. My guess is that these came in during import from CSV; we should strip these. We should also check that multiple internal spaces are compressed to one (e.g., "Luc  Andre" becomes "Luc Andre" with only one internal space).

**Comment by pbanaszkiewicz** [comment]
But there is a `strip` in the code: https://github.com/swcarpentry/amy/blob/develop/workshops/util.py#L85

**Comment by gvwilson** [comment]
Hm - there were a bunch of names in the database with leading and 
trailing spaces, which I've now removed by hand.

**Comment by pbanaszkiewicz** [comment]
Were these spaces in consecutive records?

**Comment by gvwilson** [comment]
Mmm... don't know.  Can you pull up the change log from the AMY database 
and look for all the people I touched this afternoon?

**Comment by pbanaszkiewicz** [comment]
Looking at https://amy.software-carpentry.org/workshops/log/, for example last 4 people you changed:
* https://amy.software-carpentry.org/workshops/person/10383
* https://amy.software-carpentry.org/workshops/person/10382
* https://amy.software-carpentry.org/workshops/person/10352
* https://amy.software-carpentry.org/workshops/person/10351

It seems that IDs are relatively close to each other, but looking at creation timestamp I wouldn't say they were introduced with Bulk Upload feature.

Maybe @maneesha can comment on that since she entered these people in?

Cheers

**Comment by maneesha** [comment]
Yes, I think some of those were a bit of sloppiness on my part - I didn't bulk upload but I did copy/paste which may have carried over some spaces.

Will this fix automatically strip all leading/trailing spaces from names and emails now or should I be more careful about this myself?

**Comment by pbanaszkiewicz** [comment]
@maneesha I'll strip trailing spaces in names and emails on the production just before merging this PR, so between then and the release of v1.3 (December/January) you should be more careful.
