### ISSUE TITLE
Instructor Profile Update - matching record not found even though it exists

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#619]
Possible bug?  Or maybe records don't match because of whitespace?  If so can we always strip leading/trailing whitespace?

https://amy.software-carpentry.org/workshops/profile_update/103  gives the warning that no record matches name or email but 

https://amy.software-carpentry.org/workshops/person/361 is a name match

**Comment by maneesha** [comment]
Another example:
Profile update request:  https://amy.software-carpentry.org/workshops/profile_update/94
Existing record:  https://amy.software-carpentry.org/workshops/person/8755

**Comment by gvwilson** [comment]
We're supposed to be stripping spaces - @pbanaszkiewicz, can you please 
dig into this one?

**Comment by pbanaszkiewicz** [comment]
I'll just:

1. Force `.strip()` upon save of both Person and ProfileUpdateRequest (this will fix #612 and #619)
2. Update production by stripping spaces from Person and ProfileUpdateRequest (not in migration)

Stripping will only apply to first, middle and last names, and email, since these are the crucial fields for us.

**Comment by pbanaszkiewicz** [comment]
Closing via #620.
