### ISSUE TITLE
Bulk upload must display/allow editing of user ID

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#623]
The form displayed for editing and confirmation during bulk upload does not show the user name that AMY is constructing, but data may be rejected because either the user's first or last name includes special characters, which cannot be used in user names.  The page should display the user name that AMY has matched on or constructed, and allow it to be edited.

**Comment by pbanaszkiewicz** [comment]
@gvwilson:

Why are special characters in usernames forbidden? And where?

I'm against giving option to edit username since it jumps complexity a thousand times (which should be matched to see if person exists? Username or email? When should we overwrite username? Etc. – for me it's unsolvable right now).
