### ISSUE TITLE
Integrating Invoice Request form into AMY

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#633]
NumFocus has a Google form used to submit an invoice request.
Right now we have a feature in AMY to hit a button & have that Google form open prepopulated as much as possible.

However, it is still a bit error prone because it still means I have to cross check what's been submitted on the Google form with what's in AMY.  I'd like to think about ways we can integrate this.  This would mean giving NumFocus staff access to AMY.  

Possible solution:

* Invoice button opens a form in AMY, not an external Google form with the same fields.
* Admin fills in rest of information & submits.
* NumFocus can see submission, enter in date & notes about when the invoice was sent out and when it was paid, all in AMY.  Right now they are doing this on a Google spreadsheet.
* Any of us can then go into AMY to see what the status of each workshop's invoice is.
* Include option to have actual invoice amount be calculated based on standard fee less Eventbrite ticket revenue (accessible via Eventbrite API?).  This would be an option & not automatic because sometimes because of bureaucracy and such, a site may not want the Eventbrite revenue applied against the workshop fee.

**Comment by pbanaszkiewicz** [comment]
@maneesha I'm working on this issue now. Question to you: does it happen that you submit multiple *different* invoices for one workshop?

For example: instead of using the 'breakdown if invoice amount' form field, you submit one invoice request for administrative costs and one for instructor travel costs.

(I'm wondering if the relation is one Event ↔ one invoice request, or does it happen that one Event has multiple invoices.)

**Comment by maneesha** [comment]
It is very rare but it could happen that one workshop has multiple invoices.  This could be because of what you describe, or because the host university is paying out of separate grants, or something like that.
