### ISSUE TITLE
Enhance workshop request forms for self-organized workshops

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/amy#634]
WIP

**Comment by maneesha** [comment]
For self organized workshops they should be making their own github page.  So can we have a way for them to just submit that directly into AMY, rather than filling out a form which would likely duplicate that data? The admin could then accept it which would do the same thing as "Import from URL" on the New Event page.

 What do @jduckles  @gvwilson @tracykteal think?

**Comment by gvwilson** [comment]
I like this - a one-line text box at the top of the "tell us about your 
workshop" form where they put in the URL of the site they've built, we 
harvest info, display for confirmation/editing, then into the queue it goes.

**Comment by tracykteal** [comment]
I think there's a potential time disconnect between when they're thinking about running a self-organized workshop, and we want to make sure they're OK to do it, and when they set up the workshop website. 

I would prefer that they filled out the form and we can do things like have a checkbox that says
- I will set up my own registration
- I will distribute the surveys

**Comment by pbanaszkiewicz** [comment]
@maneesha, @tracykteal, @gperu

There aren't many details as for what is a self-organized workshop on the SWC website. I've only found this: http://software-carpentry.org/workshops/request/

> In addition, the Software Carpentry Foundation charges an administration fee for workshops that it helps organize at institutions which are not partners or affiliates. For workshop requests received after September 1, 2015, these fees are: 
>
> * **If you have organized the workshop yourself** (e.g., have found instructors and are managing inquiries), we are happy to help by setting up an Eventbrite registration page and creating pre- and post-workshop assessment questionnaires. In this case, we ask for (but do not require) a donation, and recommend $500 as a suitable amount.

So which way should we go?

1. A single-field form for submitting a self-organized workshop website, or
2. a form similar to the current "Request a workshop" form, or
3. both?

°1 would be useful if most of self-organized workshop are being registered after their websites have been created.

°2 would be useful if people would tend to tell admins about self-organized workshops before they'd happen.

**Comment by gperu** [comment]
My comments:

- info given on the website: I think the indications given on the website should be updated according to what we are asking them to do

- URL submission: (agreeing with @maneesha ) ideally they should be able to summit an URL so that the event is recorded in AMY without us having to do anything else than accept. If this is not possible (i.e., if there's no way that all the info needed, such as the roles associated to the workshop, are automatically passed from the URL/workshop-request to AMY), then I'm OK doing the final editing and completing

- @tracykteal's ideas sound also fine to me

- it would be great if an automatic email could be sent to the contact person reminding them to submit (or send us) the attandance as soon as the workshop is finished (e.g., the day after the last day)

- a tick box like 'are you intending to give a donation?' 'YES/NO'; if YES, give them instructions

Whatever is implemented now could be a temporary solution to be tweaked in the near future when we gather evidence of how thisngs are going, what the faults are.

**Comment by pbanaszkiewicz** [comment]
@tracykteal alright, it turns out that current SWC workshop-request form asks the workshop will be self-organized or other type (https://amy.software-carpentry.org/workshops/swc/request/ - last question).

If you want, I can enable that question on DC form as well.

And because it's present on SWC, for now I won't go with your idea (https://github.com/swcarpentry/amy/issues/634#issuecomment-171486748), ie. I won't implement a separate form for folks to request a self-organized workshop.
