### ISSUE TITLE
Improving workflow for bulk upload

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#654]
A person named "Alpha Beta" is in the database without an email address.  We then do a bulk upload from CSV with a record "Alpha,Beta,ab@somewhere.com" followed by event and role information.

AMY reports a name collision and suggests using the email address of the person in the database to force a merge - but there isn't one:

![screen shot 2016-01-14 at 9 09 20 am](https://cloud.githubusercontent.com/assets/911566/12331608/1e24cb60-ba9f-11e5-9d5f-3752ce7713aa.png)

Go ahead and upload, then use "merge person" to reconcile - because AMY discards everything belonging to the "from" person, there's no way to select the username of the existing record *and* the email address brought in from CSV:

![screen shot 2016-01-14 at 9 10 07 am](https://cloud.githubusercontent.com/assets/911566/12331638/3f061dd4-ba9f-11e5-94db-59bcb172543a.png)

It would be really nice if the admin could select which fields to keep/discard (or even edit) on this confirmation form.

**Comment by pbanaszkiewicz** [comment]
So what do you suggest? After bulk-upload go to 2-people merge? Or just fix the 2-people merge?

**Comment by gvwilson** [comment]
Definitely fix the two-person merge; still thinking about the 
collision-with-no-email thing during upload. @maneesha, any ideas?

**Comment by pbanaszkiewicz** [comment]
I was thinking about this approach:

1. Remove all the duplication-related features we can from bulk-upload
2. Leave: matching person by email, matching event by slug, matching role by name (person doesn't have to exist in the database, but event and role do)
3. After successful bulk-upload, redirect the user to find-duplicates view (to be implemented #624)
4. Let the find-duplicates and merge-duplicates (to be fixed #654) do the rest.
5. Bonus: don't bother with usernames (if existing user), or let the algorithm generate them (if new user).

This has two advantages from my point of view:
1. we may be able to reduce the amount of code in bulk-upload
2. we won't repeat our functionality in merge-duplicates and in bulk-upload

…and one I-don't-know-if-it's-a-good-change:
1. admins will have to merge every duplicated record rather than fix the upload data

@gvwilson do you like my idea?

**Comment by gvwilson** [comment]
I like fixing things during upload (so that bad data doesn't get into 
the database in the first place), but it's not my call: @maneesha gets 
to decide.  @maneesha, preferences?

**Comment by pbanaszkiewicz** [comment]
@gvwilson merging persons is now way better; if you or @maneesha can't find any way to improve the *collision-with-no-email thing during upload* then I'm going to close this issue.

**Comment by gvwilson** [comment]
Close it - thanks.
