### ISSUE TITLE
"Update from URL" should also update URL

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#746]
If the "update from URL" function is used and a new url is entered in the popup (ie, url url hadn't already been entered for that event),  then date, location, etc. updates as expected. 

The url field itself should also update.

**Comment by narayanaditya95** [comment]
Although the `import_from_url` script updates the URL filed, the `url` itself is not returned from the `event_import` view.

I have suggested a fix at [#748](https://github.com/swcarpentry/amy/pull/748).

Cheers!

**Comment by pbanaszkiewicz** [comment]
@maneesha I think you used "Skip non-empty fields.", but you should use "Overwrite" to overwrite existing URL.

**Comment by pbanaszkiewicz** [comment]
@maneesha let me know if you want to do something about this behavior, for example change the default option from "Skip" to "Overwrite".

**Comment by narayanaditya95** [comment]
> @maneesha I think you used "Skip non-empty fields.", but you should use "Overwrite" to overwrite existing URL.

This bug is encountered when the URL field for an event is empty.
Since it is the first time that the URL field is being populated, choosing the "Skip non-empty fields" seems to be the right choice as the user is only interested in updating the empty fields, including the URL field.
Please manually test the Update from URL functionality on an event with empty URL field.

**Comment by pbanaszkiewicz** [comment]
@narayanaditya95 you're right.

The solution is to remove `data.` part from JS code in a proper place.

I'd like to also evaluate empty `object.url` to empty string instead of `None` in `event_import_update_from_url.html` line 29.

@narayanaditya95 I feel like you should make the changes and submit a new PR, since you already fixed this issue once. Will you? If you're busy I can do that.

Thanks for the help!

**Comment by narayanaditya95** [comment]
On it.
