### ISSUE TITLE
Date(?) stamp when updating record from url

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#834]
When updating an event from url, the list of instructors/helpers is recorded in the notes field with a heading that looks like a date but isn't.  For example an update I made today has the heading "UPDATE 2016-5-4:"

What is this heading supposed to be?  Can we make it be the real date of the update (i.e., UPDATE 2016-06-16:")

**Comment by pbanaszkiewicz** [comment]
@maneesha the reason why this is so ugly is because we're translating month and day numbers as integers from JavaScript into text. JavaScript is unbelievably stupid in this area (just see how many different and unpleasant solutions are to this particular problem: http://stackoverflow.com/questions/3605214/javascript-add-leading-zeroes-to-date).

We'll deal with it for v1.7.
