### ISSUE TITLE
Denote cancelled workshops in AMY

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/amy#846]
Add tag for cancelled workshops.
This should also result in the workshop being unpublished.  
(So published == has date and has location and has workshop page and  tag != "cancelled")

**Comment by apawlik** [comment]
Would it be useful to have reasons (for stats and further analysis):
* cancelled due to lack of funds
* cancelled due to problems in finding instructors
* cancelled due to venue problems [not sure if that is interesting for us, I think the first two are]
* other reasons

**Comment by narayanaditya95** [comment]
@pbanaszkiewicz 
Since we also have to record the reason behind the cancellation, we can add a `CharField` with a choice that lists the possible reason to the `Event` model.
Is this schema change good enough?

**Comment by maneesha** [comment]
@apawlik I think the potential reasons for canceling a workshop are too complex to enumerate.  

Also we are thinking of cancelled meaning that a workshop was completely planned - i.e., had instructors, a venue, registered learners, etc. and had to cancel.

If we start talking to a host about doing a workshop and they can't do it because of lack of funds, don't have a venue, etc.  then it is considered "stalled."

**Comment by apawlik** [comment]
@maneesha Yes, I agree that to enumerate all reasons is not possible. I was just wondering (based on the past experience) whether capturing how often it was due to lack of instructor vs lack of funds was interesting for us to note any patterns. Though if we define *cancelled* as all fully planned, then this is not applicable.

I think this may be a question to the Steering Committees whether we want to capture any stats on how many workshops become stalled due to lack of funds/troubles in finding instructors. The latter used to be a headache in the UK (more than the former) and knowing that was informative for SSI (but whether this is for the SCs now, it's a different question).
