### ISSUE TITLE
All trainers should be able to log in to AMY

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/amy#859]
Anyone with an instructor training badge should be able to log in to AMY.  (This may take care of itself after we finish migration/transition.)

**Comment by gvwilson** [comment]
Any progress?

**Comment by gvwilson** [comment]
@pbanaszkiewicz any progress?

**Comment by pbanaszkiewicz** [comment]
Well @gvwilson it was you who wanted to tackle this issue :-)

**Comment by gvwilson** [comment]
Yup, but my timeline has accelerate somewhat...

**Comment by chrismedrela** [comment]
There are two issues. First is that some accounts are inactive (`Person.is_active == False`). This can be solved by running the following code in production:

```python
# activate instructors accounts
instructors = Person.objects \
                    .filter(badges__name__in=['swc-instructor', 'dc-instructor']) \
                    .filter(Q(is_active=False)) \
                    .distinct()
print(instructors.all().count())  # => 196

instructors.update(is_active=True)

print(instructors.all().count())  # => 0
```
@pbanaszkiewicz can I run it?

@gvwilson The second issue is that there are still 97 people who cannot login, because they didn't share their GitHub username with us. What do we do with them? Send them an email asking for GitHub username, and then manually copy usernames from replies into AMY?

**Comment by pbanaszkiewicz** [comment]
@chrismedrela:
> @pbanaszkiewicz can I run it?

Not without @maneesha's review. You should also exclude people who have unusable password or no GitHub username, because they won't be able to log in anyway.

> What do we do with them? Send them an email asking for GitHub username, and then manually copy usernames from replies into AMY?

They can still request an update to their profiles from [an external form](https://amy.software-carpentry.org/forms/update_profile/).

**Comment by chrismedrela** [comment]
> You should also exclude people who have unusable password or no GitHub username, because they won't be able to log in anyway.

If somebody has an inactive account, they have no usable password (I checked that). So all we need to do is to exclude people without GitHub username.

So we need to run the following code on production:

```python
instructors = Person.objects \
                    .filter(badges__name__in=['swc-instructor', 'dc-instructor']) \
                    .filter(is_active=False, github__isnull=False) \
                    .distinct()
print(instructors.all().count())  # => 100

all_instructors = list(instructors.all())
instructors.all().update(is_active=True)

for p in all_instructors:
    print(p)
    p.refresh_from_db()
    p.synchronize_usersocialauth()
```

@maneesha could you review?

**Comment by pbanaszkiewicz** [comment]
Please reopen if this issue is still relevant.
